### ISSUE TITLE
Wrong insertion of yml object

### ISSUE THREAD

**Issue by stncrn** [cmprescott/ansible-xml#101]
Hello, I am having troubles inserting a complete block in an xml file.

Let's consider I have this simplified XML : 
```xml
<List>
    <Item id="id001">
        <Label>Demo Label</Label>
        <Active>1</Active>
    </Item>
</List>
```

I want to add another Item into it, as List child. So the XML should become : 
```xml
<List>
    <Item id="id001">
        <Label>Demo Label</Label>
        <Active>1</Active>
    </Item>
    <Item id="id002">
        <Label>Demo 2</Label>
        <Active>0</Active>
    </Item>
</List>
```

So I used different web [XML2YML](http://codebeautify.org/xml-to-yaml) services to convert the addtionnal XML block to a YML object, all of them giving me the same result.
My playbook task is therefore looking like this : 
```yaml
  - name: Config xml
    xml: 
        file: /tmp/export.xml
        xpath: /List
        add_children: 
          - Item:
              _Id: id002
              Label: "Demo 2"
              Active: "0"
```

But the result is not the one expected : 
```xml
<List>
    <Item id="id001">
        <Label>Demo Label</Label>
        <Active>1</Active>
    </Item>
    <Item id="id002" Label="Demo 2" Active="0"></Item>
</List>
```

When trying to insert a "bigger" object, with several childs an sub-childs, which is what I definitely need, I get this error : 
`TypeError: Argument must be string or unicode.`

As the blocks I need to insert have several levels of subchilds, for around 20~30 lines, I would like to avoid using `add_children` each time to create each child one by one.

**Comment by dagwieers** [comment]
You can do it like this as an alternative:
```yaml
  - xml:
      file: /tmp/test155.new.xml
      xpath: /List
      input_type: xml
      pretty_print: yes
      add_children:
        - "<Item id='id002'><Label>Demo 2</Label><Active>0</Active></Item>"
```
