### ISSUE TITLE
 Undefined namespace prefix\

### ISSUE THREAD

**Issue by DeanKamali** [cmprescott/ansible-xml#107]
My XML begins with the following name space: 
```
<data sql-datasource xmlns:data="http://jfreereport.sourceforge.net/namespaces/datasources/sql">
      <data property name="user"></data:property name="user">
      <data property name="password">encrypted:</data:property>
</data sql-datasource>
```

When I attempt to check the module to set the password: 

```
 - name: Modify Main Report
    xml:
      path: ./checkout/tmp/datasources/sql-ds.xml
      xpath: /sql-datasource/url
      namespaces: 
          data: "http://jfreereport.sourceforge.net/namespaces/datasources/sql"
      value: test
```
I get an error 

`failed: [localhost] (item=file-ds.xml) => {"failed": true, "item": "checkout/tmp/datasources/sql-ds.xml", "msg": "Xpath /data:sql-datasource causes a failure: Undefined namespace prefix`

**Comment by DeanKamali** [comment]
I have read the source file and found out there is a namespaces option! 

```
    xml:
      path: ./sql-ds.xml
      xpath: /data:sql-datasource/data:connection/data:url
      value: "test"
      namespaces:
          data: "http://jfreereport.sourceforge.net/namespaces/datasources/sql"
```
