### ISSUE TITLE
error: path unsupported parameter

### ISSUE THREAD

**Issue by yogeshVU** [cmprescott/ansible-xml#111]
Following is my ansible task:

```
- name: change expiration setting days
  become: true
  xml: 
    path: "{{ archiva.install_path }}/apache-archiva-{{ archiva.version }}/conf/archiva.xml"
    attribute: days
    value: 99999
    xpath: /configuration/redbackRuntimeConfiguration/configurationProperties/security/policy/password/expiration
```

```
==>: fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unsupported parameters for (xml) module: path. Supported parameters include: add_children,attribute,content,count,ensure,file,input_type,namespaces,pretty_print,print_match,set_children,value,xmlstring,xpath"}
```
