### ISSUE TITLE
xpath does not reference a node on XML with long attributes ?

### ISSUE THREAD

**Issue by JSGUYOT** [cmprescott/ansible-xml#112]
Hi, 

I have a problem for get value from XML file when file has long attributes on xpath.
If i delete attribute for LogonResponse and W-API-Session, it's work, but with, it not work.
 
**My XML file** 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<LogonResponse xmlns="http://www.ibm.com/xmlns/systems/power/firmware/web/mc/2012_10/" xmlns:ns2="http://www.w3.org/XML/1998/namespace/k2" schemaVersion="V1_5_0">
    <Metadata>
        <Atom/>
    </Metadata>
    <X-API-Session kb="ROR" kxe="false">xcBN8vwYN6J0diUPAI-iMf79p7LPkwnjQW97GwH7u-Ylt1z4cbzRaJex_AHQlltQAlx0wRtrYrbMFZX16sIenrC6WPLMeW7-POOO6YMHvh9WqbDfdEfOYIyh5q7cbYCH8rakIyA8YXT91g6h6sL2dmoElAi2upRgi-ISYadETOcrI0Sym-z6jFNPtWpUIC8_dZ3D9X0gnpwFoYz-w9JsMAUv223736x4vpAHe6jfkxM=</X-API-Session>
</LogonResponse>
```

**My tasks in ansible** 

```
- name: Register x_api_session
  xml:
    xmlstring: "{{ lookup('file', '/tmp/test.xml') }}"
    xpath: /LogonResponse/X-API-Session
    content: 'text'
  register: session

```
**Error output :** 

> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Xpath /LogonResponse/X-API-Session does not reference a node!"}

I do not know if this is a bug or not or a misunderstanding on my part ... 

Can you help me ?

Regards,

**Comment by sm4rk0** [comment]
Hi JS,

This is not a bug. The XML is has a namespace (xmlns attribute) that is implicitely applied to all elements, so you should add "namespaces" parameter and use the key (`ns` in example below) in XPath, like this:
```
- name: Register x_api_session
  xml:
    xmlstring: "{{ lookup('file', '/tmp/test.xml') }}"
    namespaces:
      ns: http://www.ibm.com/xmlns/systems/power/firmware/web/mc/2012_10/
    xpath: /ns:LogonResponse/ns:X-API-Session
    content: 'text'
  register: session
```

**Comment by sm4rk0** [comment]
BTW, is there a reason for not using `file: /tmp/test.xml` instead of `xmlstring: "{{ lookup('file', '/tmp/test.xml') }}"`?

**Comment by dagwieers** [comment]
We should definitely add a note to the docs referencing namespace-related issues. And ensure the default examples have an example. (There are not examples currently, see #108 )

**Comment by JSGUYOT** [comment]
@dagwieers : 
Thank's a lot :) it's work.
But i would like just have X-API-Session value in my register, actually, ns is present in output

**My task :** 
```
- name: Register x_api_session
  xml:
    xmlstring: "{{ token.content }}"
    namespaces:
      ns: http://www.ibm.com/xmlns/systems/power/firmware/web/mc/2012_10/
    xpath: /ns:LogonResponse/ns:X-API-Session
    content: 'text'
  register: session
```

**My output :** 
```
ok: [localhost] => {
    "session": {
        "actions": {
            "ensure": "present",
            "namespaces": {
                "ns": "http://www.ibm.com/xmlns/systems/power/firmware/web/mc/2012_10/"
            },
            "xpath": "/ns:LogonResponse/ns:X-API-Session"
        },
        "changed": false,
        "count": 1,
        "matches": [
            {
                "{http://www.ibm.com/xmlns/systems/power/firmware/web/mc/2012_10/}X-API-Session": "xcBN8vwYN6J0diUPAI-iMf79p7LPkwnjQW97GwH7u-ZhNfJ1rLmn0Z2KMvU7sj6jaOpNLqZpCKXRB8-sEQPxZd8of2JxBUUa4R9YD10XOVKqjr45So0KFPUm42eFV1V3Zap-9xoiNr8VLrt8OYo3wsOfSjzKbcWniFcXHCFRdYVXO7BannUup6r7VH66egFGJpAgWOiNl_unxFKLR0yswG3B5UDWuEmCa47BdOZZEKs="
            }
        ],
        "msg": 1
    }
}
```
I have to find out how to filter this ...


@sm4rk0 :
no reason, just for test for see if it's work better with xmlstrings ;).
Now i use xmlstrings with a variable
