### ISSUE TITLE
No idempotency when combining namespace and set_children

### ISSUE THREAD

**Issue by florianschwanz** [cmprescott/ansible-xml#123]
When combining _namespaces_ and _set_children_ attributes file modification works fine but the changed status is _changed_ even if no elements are actually modified.

```
# Set child elements for the first time
...

# Set child elements for the second time
- name: Set child elements
  xml:
    path: /tmp/ansible-xml-namespaced-beers-xml.xml
    xpath: /bus:business/ber:beers
    namespaces:
      bus: http://test.business
      ber: http://test.beers
    set_children:
      - beer: "90 Minute IPA"
      - beer: "Harvest Pumpkin Ale"
  register: set_children_again

- assert: { that: "not set_children_again|changed" } # fails
```
I created a [test case](https://github.com/atosorigin/ansible-xml/blob/set-namespaced-children/tests/test-set-namespaced-children-elements.yml) for that by combing [test-set-children-elements](https://github.com/cmprescott/ansible-xml/blob/master/tests/test-set-children-elements.yml) with fixture [ansible-xml-namespaced-beers](https://github.com/cmprescott/ansible-xml/blob/master/tests/fixtures/ansible-xml-namespaced-beers.xml).
