### ISSUE TITLE
README example (removing attribute) does not work.

### ISSUE THREAD

**Issue by jgensler8** [cmprescott/ansible-xml#20]
I am trying out the first example in the [Examples](https://github.com/cmprescott/ansible-xml#examples) section:

> Remove the subjective attribute of the rating element:
```
> xml: file=/foo/bar.xml xpath=/business/rating/@subjective ensure=absent
```

My error message:
```
msg: Couldn't delete xpath target: /business/rating/@subjective ('_ElementStringResult' object has no attribute 'attrname')
```

[Here](https://github.com/cmprescott/ansible-xml/blob/master/library/xml#L157) is where I think it is failing.

There is a test file [Here](https://github.com/cmprescott/ansible-xml/blob/master/tests/test-remove-attribute.yml) but I haven't spent time to run the tests.

**Comment by cmprescott** [comment]
What OS & Ansible version? I just tested on OS X with Ansible version 1.8.4, and the test passed.

**Comment by jgensler8** [comment]
CentOS 6.5
Ansible version 1.9.2
python-lxml  2.2.3-1.1.el6
Python 2.6.6

I have pulled commit 1f7d1c3717da1c592a878b89302695b91ca7fbef (from two days ago) and I still have the same problem.

Here is my playbook (running against another CentOS box in Vagrant)

```
---
- hosts: vagrant
  remote_user: vagrant
  tasks:
  - name: copy resources
    copy: src=files/test.xml dest=/tmp/test.xml
  - name: xml transform
    xml: file=/tmp/test.xml xpath=/business/rating/@subjective ensure=absent

```
