### ISSUE TITLE
feature request - transfer values to variable

### ISSUE THREAD

**Issue by mihai-satmarean** [cmprescott/ansible-xml#30]
The module works great on  our xml file. 
Could we use this module to get some values from the xml and use them in playbooks?
Thank you!

**Comment by h0nIg** [comment]
+1. we want to duplicate existing xml elements but we are unable to get the element. therefore we need to get / register the value of element

**Comment by h0nIg** [comment]
see https://github.com/cmprescott/ansible-xml/pull/34

**Comment by mihai-satmarean** [comment]
HI,

Does this means that we can read the values?
If yes please place a small example.

Thank you!

2015-10-07 23:31 GMT+02:00 Hans-Joachim Kliemeck <notifications@github.com>:

**Comment by h0nIg** [comment]
i rewrote the pull request and added tests/examples

**Comment by h0nIg** [comment]
i rewrote the pull request to output dict instead of plain string (same format like set_children/add_children) and added tests/examples

**Comment by h0nIg** [comment]
examples:

```
  - name: Get element attributes
    xml:
      file: /tmp/ansible-xml-beers.xml
      xpath: /business/rating
      content: 'attribute'

  - name: Get element text
    xml:
      file: /tmp/ansible-xml-beers.xml
      xpath: /business/rating
      content: 'text'
```
