### ISSUE TITLE
Cannot add (or count) children without a namespace in a namespace xml.

### ISSUE THREAD

**Issue by simonpie** [cmprescott/ansible-xml#39]
Hello,
In order to patch WSO2, I need to add a child to an element that has no namespace but whose parent has a namespace.  The following code  works perfectly with a standard xml (example file from ansible-xml) and creates a leaf `testtest` with content `blabla`:

``` yaml
    - name: Creation XSSPreventionConfig
      become: yes
      become_user: root
      xml:
        file: /tmp/ansible-xml-beers.xml
        xpath: /business/beers
        add_children:
          - XSSPreventionConfig: 
      when: true

    - name: test xml
      become: yes
      become_user: root
      xml:
        file: /tmp/ansible-xml-beers.xml
        xpath: /business/beers/XSSPreventionConfig
        add_children:
          - testtest: "blabla"
      when: true
```

Whilst the following code does not work on the same file (namespace version)

``` yaml
    - name: add child poom to beers namesspace
      become: yes
      become_user: root
      xml:
        file: /tmp/ansible-xml-namespaced-beers.xml
        xpath: /bus:business/ber:beers
        namespaces:
          bus: http://test.business
          ber: http://test.beers
          web: http://test.website
        add_children:
          - poom:
      when: true

    - name: ajout enfant a poom
      become: yes
      become_user: root
      xml:
        file: /tmp/ansible-xml-namespaced-beers.xml
        xpath: /bus:business/ber:beers/poom
        namespaces:
          bus: http://test.business
          ber: http://test.beers
          web: http://test.website
        add_children:
          - beer: "bla"
      when: true
```

This last snippet will add a `poom` child, but will not add a `beer` child to `poom`.

By the way, I have the same problem with counting beer child with namespace xml example, but I can do it fine with the basic xml.  In the namespace example, I can count the `beers` element (returns 1), but I cannot seem to be able to count the beers elements (returns 0).

**Comment by simonpie** [comment]
Found it, I have to use a local access operator in my xpath ;
```yaml
    - name: ajout enfant a poom
      become: yes
      become_user: root
      xml:
        file: /tmp/ansible-xml-namespaced-beers.xml
        xpath: /bus:business/ber:beers/*[local-name()="poom"]
        namespaces:
          bus: http://test.business
          ber: http://test.beers
          web: http://test.website
        add_children:
          - beer: "bla"
      when: true
```
May I humbly suggest adding an example with that case for beginners ?
