### ISSUE TITLE
add_children is not idempotent

### ISSUE THREAD

**Issue by mattfirtion** [cmprescott/ansible-xml#42]
When running a task to add a child element, the child element is added on each execution.

```
- name: Add child element
  xml:
    file: "/tmp/ansible-xml-beers.xml"
    xpath: /business/beers
    add_children:
      - beer: "Old Rasputin"
```

```
<?xml version='1.0' encoding='UTF-8'?>
<business type="bar">
  <name>Tasty Beverage Co.</name>
  <beers>
    <beer>Rochefort 10</beer>
    <beer>St. Bernardus Abbot 12</beer>
    <beer>Schlitz</beer>
    <beer>Old Rasputin</beer>
  <beer>Old Rasputin</beer><beer>Old Rasputin</beer><beer>Old Rasputin</beer><beer
>Old Rasputin</beer></beers>
  <rating subjective="true">10</rating>
  <website>
    <mobilefriendly/>
    <address>http://tastybeverageco.com</address>
  </website>
</business>
```
