### ISSUE TITLE
How to edit multiple attributes with same name and same tag at once?

### ISSUE THREAD

**Issue by Sparcks** [cmprescott/ansible-xml#47]
Hi

I'm stuck on a little problem and don't see this in the readme documentation.
I want to change all attributes of a certain list of tags, example:
```
<serverSettings>
	<socketAddresses>
		<socket address="10.69.14.84" port="9933" type="TCP"/>
		<socket address="10.69.14.84" port="9933" type="UDP"/>
	</socketAddresses>
</serverSettings>
```

So in this example, I want to change the _address_ attributes of the _socket_ tags.
I had following yaml code, but it doesn't seem to work:
```
   - name: Setting ip address for all smartfox servers.
     xml: 
       file:"{{item.xml_file}}"
       xpath:/serverSettings/socketAddresses/socket/*
       attribute: address
       value: "{{ip_address}}"
       with_items:
         - xml_file: "{{servers[0]}}/config/server.xml"
         - xml_file: "{{servers[1]}}/config/server.xml"
```

Can someone help me with this?
Thanks in advance!
