### ISSUE TITLE
Reading an attribute value into an ansible variable is not documented

### ISSUE THREAD

**Issue by ssbarnea** [cmprescott/ansible-xml#59]
The documentation should include a code sample that loads an attribute value into an ansible variable. I may make sense to provide a simple example for reading the `charset` attribute from insite HTML page. `html>headers>meta>charset`. Maybe even specifying what happens if it is missing.

**Comment by cmprescott** [comment]
That should definitely be included.

**Comment by wheelq** [comment]
is it possible to read the value? what is the attribute?

**Comment by kenthua** [comment]
Looks like it's [https://github.com/cmprescott/ansible-xml/blob/master/library/xml#L31](from the source)

**Comment by hdimitriou** [comment]
The xmlstring is inaccurate:

```
    - name: xml test
      xml:
        file: "{{ some_file }}"
        xpath: //some_xpath
        content: text
      register: xml_hits
```
