### ISSUE TITLE
Xpath Axes with ansible-xml

### ISSUE THREAD

**Issue by datnt11** [cmprescott/ansible-xml#77]
Hi everyone,
I am newbie in ansible programing. I would like to know there are any way to use xpath axes with ansible-xml.

About XPath Axes http://www.w3schools.com/xsl/xpath_axes.asp

XML
```
<configuration changed-seconds="1470644856" changed-localtime="2016-08-08 15:27:36 ICT">
    <access>
        <address-assignment>
            <pool>
                <name>IP-POOL</name>
                <family>
                    <inet>
                        <network>192.168.1.0/24</network>
                        <range>
                            <name>1</name>
                            <low>192.168.1.0</low>
                            <high>192.168.1.255</high>
                        </range>
                    </inet>
                </family>
            </pool>
        </address-assignment>
    </access>
</configuration>
```
TASK

```
-   name: Get exact poolname from prefix
            xml: 
                file: "{{ inventory_hostname }}-show-acces-pool.xml"  
                xpath: '//pool/family/inet[network="192.168.1.0/24"]/preceding-sibling::name[2]'
                content: 'text'
            register: exact_poolname
```
EXPECT RESULT
exact_poolname = IP-POOL
