### ISSUE TITLE
Add hierarchy of xml elements from yaml structure

### ISSUE THREAD

**Issue by sradi** [cmprescott/ansible-xml#95]
Hi,

I am currently trying out ansible-xml. There's one thing, I couldn't get working:
I am referencing a variable from a yml file, which contains a list of items, that are added as xml elements to my target file. That's easy... Now I would like to reference a variable, which contains a list, where each item again contains a list. I expected, that I could add two levels of nested xml elements at once, this way. Unfortunately I am receiving this error: 
`TypeError: Argument must be bytes or unicode, got 'list'`

Is there any way to add a full xml structure at once, with add_children?

Thanks a lot in advance!!
Stefan

**Comment by dagwieers** [comment]
Look at the example at #101, the same technique is possible for adding multiple levels.

Using the YAML input type:
```yaml
  - xml:
      file: /tmp/test156.new.xml
      xpath: /List
      pretty_print: yes
      add_children:
        - Item:
            _Id: id002
            _:
              - Label:
                  _:
                  - Name: Demo 2
                  - Source: Vinyl
              - Active: "0"
```

Using the XML input type:
```yaml
  - xml:
      file: /tmp/test156.new.xml
      xpath: /List
      input_type: xml
      pretty_print: yes
      add_children:
        - "<Item id='id002'><Label><Name>Demo 2</Name><Source>Vinyl</Source></Label><Active>0</Active></Item>"
```

If you're happy with these examples, please close this issue :-)
